// Transcribed content of the operational reference docs under `docs/`.
// Source of truth remains the PDFs; this file is re-generated by hand when
// the manuals change. See specs/filter-help-section.md for the inventory.

export type ManualBlock =
  | { type: "heading"; text: string }
  | { type: "text"; text: string }
  | { type: "list"; items: string[] }
  | { type: "callout"; tone: "info" | "warning" | "danger"; text: string };

export interface ManualSection {
  id: string;
  title: string;
  subtitle?: string;
  icon: string;
  highlight?: boolean;
  blocks: ManualBlock[];
}

export const MANUAL_SECTIONS: ManualSection[] = [
  {
    id: "apertura",
    title: "Apertura",
    subtitle: "06:00-14:00 / 07:00-15:00",
    icon: "sunrise",
    highlight: true,
    blocks: [
      {
        type: "text",
        text: "Antes de empezar cualquier turno siempre imprimir un daily con todos los vuelos del dia y tambien la hoja de extras. Ponerse al dia de que vuelos ya se han ido/llegado, que pasajero tenemos en el lounge o estamos esperando, que maletas son de que avion, los vuelos a o desde terceros paises. Entrar 5 minutos antes.",
      },
      {
        type: "text",
        text: "Siempre empezar el turno con un walkie con bateria y pinganillo. Coger preferentemente los walkies marcados con FILTRO.",
      },
      { type: "heading", text: "Tareas del turno" },
      {
        type: "list",
        items: [
          "Imprimir y ordenar Gendecs (si no estan impresas).",
          "Imprimir hoja de extras para almacen y para filtro.",
          "Gendecs de llegada: anotar si el avion se queda o se marcha. Anotar si pasan control de aduanas y fronteras.",
          "Gendecs de salida: anotar los extras que tengan y si pasa control de fronteras.",
          "Comprobar que la orden del dia anterior este correctamente introducida en el cyber y todos los vuelos cerrados. Anotar quien lo ha revisado.",
          "Turno 06:00-14:00: llegadas. Turno 07:00-15:00: salidas.",
          "Realizar las tareas pendientes que no haya podido cubrir el turno de cierre.",
        ],
      },
      {
        type: "callout",
        tone: "info",
        text: "En invierno, cuando no haya personal de sala, todas sus funciones las cubre en la medida de lo posible el personal de filtro.",
      },
    ],
  },
  {
    id: "sandwich",
    title: "Sandwich",
    subtitle: "10:00-18:00 / 11:00-19:00",
    icon: "sandwich",
    blocks: [
      {
        type: "list",
        items: [
          "Funcion de todo el equipo. Si hay llegadas y salidas, la persona de sandwich esta pendiente de la llegada de pasajeros a la terminal.",
          "Ayudar a preparar los extras de los aviones (catering, vajilla, termos).",
          "Si entran vajillas y el trabajo lo permite, ayudar a hacerlas.",
          "Si el trafico lo permite, ayudar con el turno de cierre: gendecs del dia siguiente, vajillas, filtro.",
        ],
      },
    ],
  },
  {
    id: "cierre",
    title: "Cierre",
    subtitle: "14:00-22:00 / 15:00-23:00",
    icon: "moon",
    blocks: [
      { type: "heading", text: "Tareas" },
      {
        type: "list",
        items: [
          "Hacer las Gendecs del dia siguiente.",
          "Dejar todos los datos del dia introducidos en el cyber (crew, pax y extras) y la orden del dia revisada con el nombre del que la ha revisado.",
          "Escanear Gendecs y orden del dia (salvo que queden vuelos de noche) y guardar en la carpeta FILTRO con la fecha como nombre.",
          "Si es posible, dejar las Gendecs impresas del dia siguiente en oficina por si hay vuelos pronto.",
          "Si quedan vajillas, hacerlas en la medida de lo posible. Si no, avisar al jefe de turno para notificar al turno de noche.",
        ],
      },
      { type: "heading", text: "Correos obligatorios" },
      {
        type: "list",
        items: [
          "Guardia Civil: enviar mail con las llegadas y salidas del dia. Buscar 'guardia civil' en Outlook, coger el del dia anterior, responder a todos y poner en copia a handling@mallorcair.es.",
          "Policia (FRONTERAS): enviar Gendecs del dia siguiente que pasan control de pasaportes. Buscar 'FRONTERAS' en Outlook, responder a todos cambiando la fecha y poniendo en copia a handling@mallorcair.es. Adjuntar las gendecs de paises en cuestion.",
          "RESIDUOS: aviones que lleguen de fuera de la UE (UK, USA...). Mail con numero de vuelo, matricula, pais de origen y hora en local time. Buscar 'RESIDUOS' en Outlook y responder a todos anadiendo handling de MCR.",
        ],
      },
    ],
  },
  {
    id: "funciones",
    title: "Funciones generales",
    icon: "book",
    blocks: [
      {
        type: "text",
        text: "Informacion comun a todos los turnos sobre preparacion y material.",
      },
      {
        type: "list",
        items: [
          "Imprimir daily con todos los vuelos + hoja de extras al inicio del turno.",
          "Ponerse en situacion: vuelos llegados/salidos, pax en lounge, equipaje por matricula, terceros paises.",
          "Walkie con bateria + pinganillo (preferentemente los marcados FILTRO).",
          "Entrar 5 minutos antes del turno.",
        ],
      },
    ],
  },
  {
    id: "hojas-maletas",
    title: "Hojas de maletas",
    icon: "luggage",
    blocks: [
      {
        type: "text",
        text: "Preparacion de carpetas con hojas de conteo de equipaje de bodega para las salidas con pasajeros del dia siguiente.",
      },
      {
        type: "list",
        items: [
          "Imprimir una orden del dia del dia siguiente.",
          "Senalar las salidas con pax y coger las carpetas necesarias, marcarlas con la matricula.",
          "Meter en cada carpeta su hoja de conteo y etiquetas con matricula y numero de vuelo.",
          "Leer el documento del segundo cajon de recepcion sobre el tema.",
          "Al final del dia, sin salidas pendientes, escanear las hojas y guardarlas en la carpeta FILTRO > HOJAS CONTROL EQUIPAJE.",
        ],
      },
      {
        type: "callout",
        tone: "info",
        text: "En verano con mucho volumen: preparar el dia anterior solo las del turno de manana y las de la tarde segun salgan los vuelos el mismo dia.",
      },
    ],
  },
  {
    id: "conducta",
    title: "Manual de conducta",
    icon: "shield",
    blocks: [
      {
        type: "list",
        items: [
          "Movil solo con justificacion y permiso del coordinador o jefe de turno.",
          "No entrar a un turno 5 o 10 minutos tarde por ir con un cafe en la mano.",
          "Tiempo de descanso: 30 minutos. No excederse. Ejemplo: turno 06:00 -> descanso a las 10:00.",
          "No formar grupitos hablando durante el servicio.",
          "Avisar al coordinador cuando se tome descanso o se ausente un momento (no es pedir permiso).",
        ],
      },
      {
        type: "callout",
        tone: "danger",
        text: "No se puede hacer uso del movil sin permiso expreso del coordinador o jefe de turno.",
      },
    ],
  },
  {
    id: "uniformidad",
    title: "Uniformidad",
    icon: "shirt",
    blocks: [
      {
        type: "list",
        items: [
          "Uniforme completo: camisa, pantalones, americana, deportivas y panuelo (chicas). Si no se puede usar panuelo, presentar justificante medico a direccion.",
          "Ir aseado.",
          "Pelo limpio y recogido.",
          "Cara limpia y sutilmente maquillada. Sin colores llamativos (rojos, fucsias).",
          "Unas limpias y sin colores demasiado chillones.",
          "No llevar chaquetas que no sean la de MCR.",
          "Colonias suaves.",
        ],
      },
    ],
  },
  {
    id: "atencion-cliente",
    title: "Atencion al cliente",
    icon: "userCheck",
    blocks: [
      { type: "heading", text: "Recepcion" },
      {
        type: "list",
        items: [
          "Salir a recibirles.",
          "Antes de preguntar destino: 'How are you sir or madam?', 'May I kindly ask you to tell me your flight details?', 'May you be so kind sharing with me the flight registration? Company?'.",
          "Encargarse de las maletas (pedir cuales van en cabina o bodega).",
          "Identificar su avion (preguntar a donde vuelan).",
          "Pedir documentacion (PASAPORTE / ID) antes de mandar las maletas al avion.",
          "Si no son nuestros, no atenderlos.",
          "En llegadas: encargarse de sus maletas y confirmar si tienen transporte esperando.",
          "Indicar donde esta el lounge y los banos.",
        ],
      },
    ],
  },
  {
    id: "atencion-tripulacion",
    title: "Atencion a tripulacion",
    icon: "briefcase",
    blocks: [
      {
        type: "text",
        text: "SIEMPRE comprobar los extras con ellos, preguntar cuando los quieren (hay casos que prefieren dejar el catering en la nevera el maximo tiempo posible, sobre todo en verano) y ofrecer hielo.",
      },
      {
        type: "text",
        text: "Acompanarlos siempre que se pueda hasta la oficina o el lounge.",
      },
      { type: "heading", text: "Con pax" },
      {
        type: "list",
        items: [
          "Al llegar los pilotos, comunicarles si tenemos a sus pax y llevarles hasta ellos o indicar donde estan.",
          "Preguntar cuando quieren las maletas (si conocen a los pax, doble-check de cabina/bodega).",
          "Preguntar cuando quieren embarcar.",
        ],
      },
      { type: "heading", text: "Sin pax" },
      { type: "text", text: "Acordarse de los extras." },
    ],
  },
  {
    id: "equipaje",
    title: "Equipaje",
    icon: "luggage",
    blocks: [
      {
        type: "list",
        items: [
          "Aclarar cuales van en bodega y cuales en cabina.",
          "Bodega: etiquetar con HOLD LUGGAGE para que puedan pasar.",
          "Cabina: pasa a la vez que los pax. Si nos dejan cosas, etiquetarlas con CABINA + MATRICULA en etiquetas blancas.",
          "Llegada: si los pax se van o esperan transporte, etiquetar el carro con MATRICULA + LLEGADA (puede haber tambien las de salida).",
        ],
      },
      {
        type: "callout",
        tone: "danger",
        text: "BODEGA ABIERTA (PC12, BE20, B350, TBM...): NO se pueden enviar maletas sin los pax. No etiquetar individualmente. Si nos traen maletas antes de los pasajeros, dejarlas en carros con etiqueta MATRICULA + SALIDA (el vuelo puede llegar con otras maletas).",
      },
    ],
  },
  {
    id: "transporte",
    title: "Transporte",
    icon: "car",
    blocks: [
      {
        type: "list",
        items: [
          "Identificar a quien vienen a buscar. Normalmente los conductores entran hasta recepcion y piden informacion. Si el vuelo es nuestro, informar de la hora de llegada; si es de otro handling, indicar handling y oficina.",
          "Llevar las maletas correspondientes. Casos especiales: pax del mismo vuelo en coches distintos -> SEPARAR MALETAS.",
          "Guiar al pax hasta el coche.",
          "Empresas de transporte que traen pasajeros de salida: solo atender si vuelan con nosotros. Identificar primero si son de Mallorcair.",
        ],
      },
    ],
  },
  {
    id: "coche",
    title: "Coche alquilado o privado",
    icon: "key",
    blocks: [
      {
        type: "list",
        items: [
          "Entregar llave y contrato si hay.",
          "Dejar el coche listo en la puerta. En verano y con el avion en tierra, aire puesto para que este fresquito.",
          "Entregar ticket de parking si lo tenemos nosotros.",
          "Pagar parking en ALGUNOS casos (ej: siempre europcar).",
          "En pax de salida que quieran devolver el coche al alquiler: ofrecer ir a buscarles a la terminal tras la devolucion. Companias habituales: Hertz, Avis, Okcar.",
          "Sixt y Europcar: suelen dejar el coche en aviacion general.",
          "Roig, Vanrell: tambien dejan y recogen en aviacion general.",
        ],
      },
    ],
  },
  {
    id: "catering",
    title: "Catering",
    icon: "catering",
    blocks: [
      {
        type: "list",
        items: [
          "Revisar con los de AIRE.",
          "Etiquetar las cajas con la MATRICULA y la cantidad de cajas (1/3, 2/3...).",
          "Avisar a companeros y coordinadores de que ha llegado X catering y comunicar cuantas cajas lleva cada uno.",
        ],
      },
      {
        type: "callout",
        tone: "warning",
        text: "Pedidos NetJets: fijarse bien en la numeracion, suelen cambiar solo algunos numeros. Identificarlos con su correspondiente avion.",
      },
    ],
  },
  {
    id: "vajillas",
    title: "Vajillas",
    icon: "dishes",
    blocks: [
      {
        type: "list",
        items: [
          "Apuntar en la gendec de LLEGADA cuando nos dejen una vajilla si el avion se queda. Si es vajilla express, anotarla en la gendec de SALIDA y comunicar el precio al jefe de turno.",
          "Apuntar la vajilla en NOTAS del CyberMax.",
          "Con el movil de coordinacion, hacer foto de la vajilla tal como llega.",
          "Ensenar la vajilla al coordinador: el pone el precio. Algunas companias (VJT, VJH) no pagan.",
          "Etiquetar bien los contenedores.",
          "Hacer las vajillas a mano siempre que ponga HAND WASH.",
          "Guardar la vajilla ordenada, con todo el cristal envuelto en papel de cocina y los cubiertos en bolsa zip (o papel de cocina si no hay).",
          "Una vez lavada, apuntar en la libreta de control de vajillas (en el almacen) con el precio y quien la ha hecho. Dejarla en el almacen.",
          "Si se lava en lavavajillas, dejar un Post-it con la matricula en el lavavajillas por si se termina y alguien no ha podido cerrar.",
          "Si se rompe algo de una vajilla, anotarlo en NOTAS para que avisen a la tripulacion.",
          "No dejar mas de una vajilla escurriendo en el mismo sitio.",
        ],
      },
      {
        type: "callout",
        tone: "danger",
        text: "Las vajillas SUCIAS se dejan en la cocina para que se vea. Bajo ningun concepto se dejan las vajillas sucias en el almacen.",
      },
    ],
  },
  {
    id: "extras",
    title: "Extras",
    icon: "package",
    blocks: [
      {
        type: "list",
        items: [
          "Todos los extras que dejen los aviones, apuntarlos en las gendecs y en NOTAS en el CyberMax.",
          "Las vajillas tienen que quedar limpias y los termos vacios y enjuagados.",
          "Todos los extras que nos dejen para guardar deben ir etiquetados con la matricula. Si no vienen etiquetados, coger un Post-it, anotar la matricula y pegarlo con celo al termo, bolsa, contenedor.",
          "Se pueden dejar cosas en nevera, almacen o congelador. Especificar en gendec y notas. TODO ETIQUETADO (ej: bolsa congelador, caja almacen).",
          "Llevar siempre los extras impresos junto con el daily.",
          "Tener en cuenta las prensas: comprobar que estan impresos y son correctos.",
          "Cada vez que salgan pilotos, comprobar que se lo llevan todo.",
          "Si piden hielo, agua o cafe fuera de extras, comunicarlo a oficina.",
        ],
      },
    ],
  },
  {
    id: "policia-gc",
    title: "Policia Nacional / Guardia Civil",
    icon: "police",
    blocks: [
      {
        type: "list",
        items: [
          "Policia: vuelos de terceros paises extracomunitarios (fuera de EU). SELLAR PASAPORTE.",
          "Guardia Civil: vuelos de terceros paises TODOS (Suiza, Noruega, Basilea LFSB y algunos del este). Comprobar con el mapa / listado oficial.",
          "Si alguno no esta media hora antes de llegada o salida: LLAMAR para avisar.",
          "Siempre tienen que revisar a los pax. Preguntar si quieren ver a los pilotos.",
          "Si sabemos que los pax llegan con perros, avisar al guardia civil.",
        ],
      },
      {
        type: "callout",
        tone: "danger",
        text: "ARMAS: hay pax que llegan o se van con armas. Hacer llegar la documentacion a la guardia civil. Cuando llegan los pax, uno de los pisteros entra las armas y se queda con ellos hasta que acaban la revision.",
      },
    ],
  },
  {
    id: "llegadas",
    title: "Llegadas",
    icon: "landing",
    blocks: [
      {
        type: "list",
        items: [
          "Comprobar que los nombres de los pasajeros estan bien y que el numero de pax coincide con el que tenemos.",
          "Si el numero es MENOR al previsto: tachar el nombre en la gendec y poner el numero correspondiente de pax.",
          "Si el numero es MAYOR: pedir pasaporte/ID a la persona nueva y anotar todos sus datos.",
          "En CUALQUIERA de los dos casos, avisar a oficina de la cantidad de pax real para que la factura sea correcta.",
        ],
      },
    ],
  },
  {
    id: "salidas-trablisa",
    title: "Paso por filtro / Trablisa (Salidas)",
    icon: "takeoff",
    blocks: [
      {
        type: "list",
        items: [
          "Mismo procedimiento que llegadas cuando tenemos un numero de pax imprevisto. SIEMPRE AVISAR A OFICINA.",
          "SIEMPRE que vaya a pasar algo por Trablisa, avisar al coordinador de pista para que envie a alguien a por los extras, pilotos, pax.",
          "Al enviar catering, maletas, etc., avisar a Trablisa para que activen la cinta y sepan la matricula. Maletas: poner una M en la gendec para que ambas partes sepan que ya han pasado.",
          "Cuando pasa la tripulacion: quedarse con la persona de Trablisa, pedir al piloto que se acerque con su crew ID y comprobar entre dos que los datos son correctos. No coger el crew ID (puede llevar a confusion); el piloto debe estar presente.",
          "Pedir pasaporte o ID a cada pasajero. Si vuelan a terceros paises, tiene que ser pasaporte (lo sella la policia).",
          "Si hay que sellar pasaporte: una vez comprobado con Trablisa NO devolverlo al pax; entregarlo a un companero de pista para que se lo lleve a la policia.",
          "Ayudar a los pasajeros a dejar sus pertenencias en las bandejas. Botas, tacones o zapatos que puedan pitar: indicar quitarselos y ofrecer calcetines de plastico.",
        ],
      },
    ],
  },
  {
    id: "filtro-oficina",
    title: "Filtro / Oficina",
    icon: "office",
    blocks: [
      {
        type: "list",
        items: [
          "Si los pilotos piden informacion de TOBT, TSAT, etc: indicarles que hablen con los coordinadores o acompanarles a oficina.",
          "Si piden toilet service, fuel, etc: acompanarles a oficina (desde ahi se piden los servicios).",
          "Si pax o tripulantes necesitan taxi: comunicarlo a oficina indicando hotel / direccion y si pagan ellos o va en factura.",
        ],
      },
    ],
  },
  {
    id: "crossroads",
    title: "Crossroads",
    subtitle: "Catering NetJets",
    icon: "globe",
    blocks: [
      {
        type: "text",
        text: "Pagina donde buscar y saber que caterings (aparte de flores, revistas, prensa extra) hay para cada vuelo.",
      },
      {
        type: "text",
        text: "URL: suppliers.netjets.com/crossroads-catering/crossroads-catering-web/do/home",
      },
      { type: "heading", text: "Proceso" },
      {
        type: "list",
        items: [
          "Aparecen caterings pendientes de confirmar por AIRE y los confirmados con numero de pedido + version.",
          "Al anadir un catering, suelen mandar notificacion al mail de handling con asunto ORDER NOTIFICATION.",
          "ORDER NUMBER: aparece en LOGISTICS junto a la ficha del vuelo.",
          "CREW/PAX order: para quien es el pedido.",
          "DELIVERY DATE/TIME: dia y hora del catering.",
          "Para CREW meals: click en order number -> coger nombre de un tripulante -> buscar en LOGISTICS por nombre -> etiquetar crew meal con la matricula.",
          "Para PAX caterings: buscar por destination airport + delivery time (30 min antes de la salida) y cruzar con LOGISTICS.",
        ],
      },
      {
        type: "callout",
        tone: "warning",
        text: "A veces los pedidos de Crossroads llevan REVISTAS o FLORES. TENER MUCHO CUIDADO.",
      },
    ],
  },
  {
    id: "gendecs",
    title: "Gendecs",
    subtitle: "Declaracion general",
    icon: "doc",
    blocks: [
      {
        type: "text",
        text: "Informacion de tripulacion y pasajeros que viajan en el avion. Todo avion necesita GENDECS para entrar o salir de LEPA.",
      },
      { type: "heading", text: "Datos obligatorios" },
      {
        type: "list",
        items: [
          "Nombre completo (piloto / pasajero).",
          "Pasaporte o ID.",
          "Fecha de nacimiento.",
          "Nacionalidad.",
        ],
      },
      { type: "heading", text: "Donde encontrar la info" },
      {
        type: "list",
        items: [
          "Principalmente, en la pestana GenDec del CyberMax (apartado COMUNICACIONES).",
          "Si no esta: ir a HANDLING, abrir el ultimo update colgado, doble-click abre el MAIL.",
          "Dentro del mail: puede venir escrita directamente o en PDF adjunto (GENERAL DECLARATION WITH PAX.pdf).",
        ],
      },
      { type: "heading", text: "Al abrir el PDF, fijarse siempre en" },
      {
        type: "list",
        items: [
          "Matricula del avion.",
          "Numero de vuelo (especialmente con JFA / FJO / FLJ / VJH / VJT).",
          "Fecha del viaje.",
          "Si es informacion de llegada o de salida (pueden cambiar pilotos y pax entre patas).",
        ],
      },
      { type: "heading", text: "Donde introducirla" },
      {
        type: "list",
        items: [
          "CyberMax -> pestana GENDECS (a la derecha del todo).",
          "SALIDA: datos de la salida.",
          "LLEGADA: datos de la llegada.",
          "MANTENIMIENTO: no se utiliza.",
        ],
      },
      { type: "heading", text: "Si no tenemos la info" },
      {
        type: "list",
        items: [
          "Buscar en MAIL por matricula + numero de vuelo.",
          "Si no, ir al ultimo Handling Request-UPDATE en HANDLING y responder a todos.",
          "Usar la FIRMA '1P PETICION GENDECS', firmar con nuestro nombre y enviar.",
          "En la pestana GENDECS del cyber, escribir SOLICITADA en ARR o DEP.",
        ],
      },
      {
        type: "callout",
        tone: "warning",
        text: "Copiar-pegar de VJH, VJT y NetJets: formato extrano. La seleccion salta entre pilotos. Ir casilla por casilla o escribir a mano.",
      },
      {
        type: "callout",
        tone: "warning",
        text: "Nacionalidad UK o USA: viene en dos lineas. Al pegar se desmonta toda la info. Cuidado al borrar lo no necesario.",
      },
    ],
  },
  {
    id: "netjets",
    title: "NetJets",
    icon: "doc",
    blocks: [
      {
        type: "text",
        text: "Info de NJE en el HANDLING LOGISTICS REPORT. Buscar LOGISTICS en el mail.",
      },
      {
        type: "callout",
        tone: "warning",
        text: "ID alemanes: al pegar, el ID se solapa con el pasaporte. 'Natl. LID729W7V76' -> borrar lo no necesario -> L729W7V76.",
      },
      { type: "heading", text: "Numero de crew/pax diferente al daily" },
      {
        type: "text",
        text: "Si la gendec llega con otros numeros (ej: daily dice 3 CREW / 5 PAX, gendec 2 CREW / 6 PAX), ir al CYBER y cambiar los datos a lo real: CREW 2 / PAX 6.",
      },
    ],
  },
  {
    id: "timeair",
    title: "TimeAir / TIE",
    icon: "doc",
    blocks: [
      {
        type: "text",
        text: "Esta compania lo hace diferente al resto. Dentro del correo esta toda la informacion.",
      },
      {
        type: "list",
        items: [
          "Pinchar en 'click here' -> abre ventana con los datos.",
          "Pinchar en 'GENDEC documents can be downloaded HERE' -> aparece toda la informacion.",
        ],
      },
    ],
  },
  {
    id: "sop-equipaje",
    title: "SOP Equipaje Controlado",
    subtitle: "MLR-OPS-BAG-01 V1.00",
    icon: "shieldAlert",
    highlight: true,
    blocks: [
      { type: "heading", text: "Objetivo" },
      {
        type: "text",
        text: "Garantizar que cada bulto que viaja en bodega ha sido contado, inspeccionado y reconciliado desde la entrega del pasajero hasta la carga en la bodega del avion.",
      },
      { type: "heading", text: "Responsabilidad del conteo" },
      {
        type: "text",
        text: "El conteo solo puede realizarlo el agente designado en cada fase. El personal de apoyo puede manipular equipaje pero no contar ni proporcionar cifras verbales.",
      },
      { type: "heading", text: "FASE 1 - FILTRO (seguridad)" },
      {
        type: "list",
        items: [
          "PASO 1 Recepcion: contar bultos uno por uno, verificar vuelo, identificar con matricula y registrar en FILTRO PARCIAL.",
          "PASO 2 Antes de Rayos X: recontar, verificar inspeccion, registrar en FILTRO FINAL y entregar hoja a Pista.",
        ],
      },
      {
        type: "callout",
        tone: "danger",
        text: "Si FILTRO PARCIAL != FILTRO FINAL -> detener proceso.",
      },
      { type: "heading", text: "FASE 2 - PISTA (rampa)" },
      {
        type: "list",
        items: [
          "PASO 3 Recepcion desde filtro: contar cada bulto y confirmar carga en vehiculo(s). Registrar en PISTA PARCIAL.",
          "Traslado en varios vehiculos: el control sigue siendo unico y total por vuelo.",
          "PASO 4 A pie de avion: recuento total antes de cargar en bodega. Registrar en PISTA FINAL.",
        ],
      },
      {
        type: "callout",
        tone: "danger",
        text: "Si PISTA PARCIAL != PISTA FINAL -> NO cargar.",
      },
      { type: "heading", text: "Cambios de ultima hora (bodega -> cabina)" },
      {
        type: "text",
        text: "Si un bulto cambia a cabina tras el conteo final: descontarlo del total, informar al comandante y anotarlo en la hoja de control.",
      },
      { type: "heading", text: "Total final de bultos" },
      {
        type: "callout",
        tone: "danger",
        text: "El total debe coincidir entre FILTRO FINAL y PISTA FINAL. Si hay diferencia -> operacion detenida hasta aclarar.",
      },
      { type: "heading", text: "Registro documental obligatorio" },
      {
        type: "list",
        items: [
          "Escanear la hoja y adjuntarla en Cyber.",
          "Tomar foto del carro cargado y adjuntarla en Cyber.",
          "El vuelo no se considera cerrado hasta completar estos registros.",
        ],
      },
      { type: "heading", text: "Firmas obligatorias" },
      {
        type: "list",
        items: [
          "Filtro: confirma que el equipaje fue inspeccionado.",
          "Pista: confirma que el equipaje cargado coincide.",
          "Comandante: acepta la carga declarada.",
        ],
      },
      { type: "heading", text: "Normas fundamentales" },
      {
        type: "list",
        items: [
          "No marcar sin contar fisicamente.",
          "No confiar en conteos verbales.",
          "No cargar sin conteo final de pista.",
          "No autorizar salida con discrepancias.",
        ],
      },
      { type: "heading", text: "Resumen rapido" },
      {
        type: "list",
        items: [
          "Filtro - Parcial: equipaje recibido de pasajeros. Final: equipaje antes de rayos X.",
          "Pista - Parcial: equipaje recibido desde filtro. Final: equipaje junto al avion antes de cargar.",
        ],
      },
    ],
  },
  {
    id: "hojas-control-equipaje",
    title: "Hoja de control de equipaje (plantilla)",
    icon: "doc",
    blocks: [
      {
        type: "text",
        text: "Estructura de la hoja fisica de control (ES y ENG). Cada fila del formulario.",
      },
      { type: "heading", text: "Cabecera" },
      {
        type: "list",
        items: [
          "Fecha.",
          "Numero de vuelo.",
          "Destino.",
          "Matricula.",
        ],
      },
      { type: "heading", text: "Contadores" },
      {
        type: "list",
        items: [
          "Total bultos.",
          "Filtro parcial.",
          "Filtro final.",
          "Pista parcial.",
          "Pista final.",
          "Totales pista.",
        ],
      },
      { type: "heading", text: "Firmas (x3)" },
      {
        type: "list",
        items: [
          "Filtro: firma + nombre + hora.",
          "Pista: firma + nombre + hora.",
          "Comandante: firma + nombre + hora.",
        ],
      },
    ],
  },
  {
    id: "aparcamiento-pmi",
    title: "Aparcamiento empleados PMI",
    subtitle: "Condiciones Aena",
    icon: "parking",
    blocks: [
      { type: "heading", text: "Normas generales" },
      {
        type: "list",
        items: [
          "Todos los abonos son NOMINATIVOS, PERSONALES e INTRANSFERIBLES, para uso dentro de la jornada laboral.",
          "Para tramitar la solicitud: mostrar Tarjeta de identificacion Aeroportuaria (personal aeropuerto) o Tarjeta de Tripulante (personal vuelo).",
          "Autorizacion valida para UN SOLO VEHICULO. Si no traes el autorizado, comunicar a la oficina de Control de Abonados.",
          "Solo se permite abono en UN UNICO aeropuerto. Varios simultaneos -> retirada inmediata de uno.",
          "La tarjeta de abonado es para uso personal e intransferible. Uso no laboral -> sancion o retirada definitiva.",
          "Devolver la tarjeta al finalizar la vinculacion laboral.",
        ],
      },
      { type: "heading", text: "Estancia maxima" },
      {
        type: "callout",
        tone: "warning",
        text: "2 dias consecutivos desde entrada (7 dias para tripulaciones). Exceso: justificar con antelacion a pmi.com.aparcamientos@aena.es. Siempre se cobra el exceso segun tarifas. Estancias mas largas solo en Abonados B.",
      },
      { type: "heading", text: "Sanciones progresivas" },
      {
        type: "list",
        items: [
          "1a vez: amonestacion + advertencia.",
          "2a vez: 3 meses sin parking + advertencia.",
          "3a vez: 6 meses sin parking + advertencia.",
          "4a vez: retirada indefinida.",
        ],
      },
      { type: "heading", text: "Contactos" },
      {
        type: "list",
        items: [
          "Gestion abonados: gestion-parking.pmi@easparking.com",
          "Justificar excesos: pmi.com.aparcamientos@aena.es",
        ],
      },
      {
        type: "callout",
        tone: "danger",
        text: "Danos voluntarios a las instalaciones: revocacion inmediata del abono, sin devolucion, y Aena emprendera acciones legales.",
      },
    ],
  },
];
