// Minimal factories for tests. Domain types have many fields; tests only
// care about a handful at a time, so factories give sane defaults and let
// each test override just what it needs.

import type { FlightView, FlightViewService } from "@/types/v2";

export function makeFlight(overrides: Partial<FlightView> = {}): FlightView {
  const callsign = overrides.callsign ?? "NJE123CK";
  return {
    id: "v-1",
    visitId: "v-1",
    arrivalMovementId: "m-arr-1",
    departureMovementId: "m-dep-1",
    daySheetId: "2025-01-01",
    callsign,
    // Default arrival/departure callsigns to the primary so existing tests
    // that only pass `callsign` keep working.
    arrivalCallsign: overrides.arrivalCallsign ?? callsign,
    departureCallsign: overrides.departureCallsign ?? callsign,
    registration: "CS-DXX",
    aircraftType: "GLEX",
    origin: "LFPB",
    eta: "08:00",
    arrivalDate: null,
    destination: "EGGW",
    etd: "10:30",
    departureDate: null,
    arrivalInstant: null,
    departureInstant: null,
    parking: "P-12",
    tobt: null,
    state: "PARKED",
    isOvernight: false,
    crewArrival: 2,
    crewArrivalReal: null,
    paxArrival: 4,
    paxArrivalReal: null,
    crewDeparture: 2,
    crewDepartureReal: null,
    paxDeparture: 4,
    paxDepartureReal: null,
    paxArrBagsChecked: 0,
    paxArrBagsCabin: 0,
    paxArrBagsState: "NOT_REQUESTED",
    paxArrTransportType: "NONE",
    paxArrTransportState: "NOT_REQUESTED",
    paxArrState: "NOT_REQUESTED",
    paxDepBagsChecked: 0,
    paxDepBagsCabin: 0,
    paxDepBagsState: "NOT_REQUESTED",
    paxDepTransportType: "NONE",
    paxDepTransportState: "NOT_REQUESTED",
    paxDepState: "NOT_REQUESTED",
    crewArrLocation: "NONE",
    crewDepLocation: "NONE",
    fuelState: "NOT_REQUESTED",
    fuelRequestedAt: null,
    fuelServedAt: null,
    toiletState: "NOT_REQUESTED",
    toiletRequestedAt: null,
    toiletCompletedAt: null,
    linkedFlightId: null,
    notes: null,
    assignedToId: null,
    assignedToName: null,
    rqstNumber: null,
    flightCategory: "COMMERCIAL",
    modifiedFlag: false,
    petCount: 0,
    services: [],
    lostItems: [],
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
    ...overrides,
  };
}

export function makeService(overrides: Partial<FlightViewService> = {}): FlightViewService {
  return {
    id: "svc-1",
    flightId: "v-1",
    visitId: "v-1",
    type: "CATERING",
    state: "PENDING",
    target: "ARRIVAL",
    reference: null,
    customName: null,
    origin: null,
    arrivedAt: null,
    deliveredAt: null,
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
    ...overrides,
  };
}
