/**
 * NetJets "Handling Logistics Report" parser.
 *
 * The PDF is generated by the ALS system. Naive linear text extraction destroys
 * the structure: this is a TRANSPOSED layout (landscape 792x612) where field
 * labels (Expiry, Country, Number, Doc Type, DOB, GN, PIC/SIC/FA, Surname,
 * Name, Pax, Tail #, AC Type, To, From, ETA, ETD, Call Sign, Rqst #, ETD Date)
 * sit in a vertical column on the LEFT (x ~ 108-127) and each PERSON is its
 * own VERTICAL column to the right. Multiple flights coexist horizontally on
 * the same page, anchored at distinct x positions.
 *
 * We pull text items with x/y coordinates via pdfjs-dist v4 legacy build, then:
 *   1. detect flight anchor x positions from the Rqst # row (y ~ 78),
 *   2. detect person column x positions inside each flight's x range from the
 *      Surname/Name/DOB rows,
 *   3. for each person column, read each field cell by Y band + X range,
 *   4. reconstruct multi-chunk cells (e.g. "Steinbrugg" + "er" → "Steinbrugger",
 *      "United" + "Kingdom" → "United Kingdom") by joining items inside the
 *      column's x slice ordered by x,
 *   5. handle the special cases documented in the brief (NID with embedded
 *      number, Country with embedded Expiry date, pets, ferry/cancelled).
 *
 * Page 6 of the report is a legal/stamp page and is skipped.
 */

import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';

const Y_TOL = 6;          // tolerance for matching items to a labelled Y row
const COLUMN_GAP = 12;    // x gap above which two items are different person columns

const PERSON_Y = {
  expiry:    722,
  country:   676,
  docNumber: 596,
  docType:   577,
  dob:       526,
  gn:        507,
  role:      486,
  surname:   436,
  name:      356,
};

const FLIGHT_Y = {
  pax:        334,
  tailAndAc:  291,
  to:         262,
  from:       233,
  etdEta:     172,
  callSignRow:123,
  rqst:       78,
  statusType: 71,
  bottomRow:  24,
  modified:   29,
};

const MONTHS = {
  Jan: '01', Feb: '02', Mar: '03', Apr: '04', May: '05', Jun: '06',
  Jul: '07', Aug: '08', Sep: '09', Oct: '10', Nov: '11', Dec: '12',
};

function parseDayMonYear(s) {
  if (!s) return null;
  const m = s.trim().match(/^(\d{1,2})\s+([A-Z][a-z]{2})\s+(\d{4})$/);
  if (!m || !MONTHS[m[2]]) return null;
  return `${m[3]}-${MONTHS[m[2]]}-${m[1].padStart(2, '0')}`;
}

function parseMonDayYear(s) {
  if (!s) return null;
  const m = s.trim().match(/^([A-Z][a-z]{2})\s+(\d{1,2})\s+(\d{4})$/);
  if (!m || !MONTHS[m[1]]) return null;
  return `${m[3]}-${MONTHS[m[1]]}-${m[2].padStart(2, '0')}`;
}

function parseEtdEtaCell(s) {
  if (!s) return [null, null];
  const matches = [...s.matchAll(/(\d{2})(\d{2})\s*Z/g)];
  return [
    matches[0] ? `${matches[0][1]}:${matches[0][2]}` : null,
    matches[1] ? `${matches[1][1]}:${matches[1][2]}` : null,
  ];
}

function parseGeneratedAt(s) {
  if (!s) return null;
  const m = s.match(/(\d{2})\/(\d{2})\/(\d{4})\s+(\d{2})(\d{2})/);
  if (!m) return null;
  return `${m[3]}-${m[1]}-${m[2]}T${m[4]}:${m[5]}:00Z`;
}

function nearY(items, targetY) {
  return items.filter((it) => Math.abs(it.y - targetY) <= Y_TOL);
}

function inXRange(items, xMin, xMax) {
  return items.filter((it) => it.x >= xMin - 0.5 && it.x < xMax);
}

// Left-side label band: items whose x is below this are field labels
// ("Surname", "Name", "Country", ...) and never carry person values.
const LEFT_LABEL_BAND_MAX = 135;

// Assign each item in `candidates` to its nearest anchor (within `pageAnchors`),
// then return only items whose nearest anchor is exactly `targetAnchor`. The
// page-wide anchor set prevents items from adjacent flights leaking into the
// rightmost person column of a flight (no anchor to the right inside the same
// flight ⇒ would otherwise act as a sink).
function pickByNearestAnchor(candidates, targetAnchor, pageAnchors) {
  return candidates.filter((it) => {
    if (it.x < LEFT_LABEL_BAND_MAX) return false;
    let bestA = null;
    let bestD = Infinity;
    for (const a of pageAnchors) {
      const d = Math.abs(it.x - a);
      if (d < bestD) {
        bestD = d;
        bestA = a;
      }
    }
    return bestA === targetAnchor;
  });
}

function joinByX(items) {
  const sorted = items.slice().sort((a, b) => a.x - b.x);
  let result = '';
  for (const it of sorted) {
    const t = it.text;
    if (!t) continue;
    if (result === '') {
      result = t;
    } else if (/^[a-z]/.test(t)) {
      // Lower-case start ⇒ overflow continuation of the previous chunk
      // (e.g. "Steinbrugg" + "er" → "Steinbrugger", "Liechtenstei" + "n").
      // No separator inserted.
      result += t;
    } else {
      result += ' ' + t;
    }
  }
  return result.replace(/\s+/g, ' ').trim();
}

async function extractPdfPages(buffer) {
  const data = new Uint8Array(buffer);
  const pdf = await getDocument({ data, isEvalSupported: false, disableFontFace: true }).promise;
  const pages = [];
  for (let p = 1; p <= pdf.numPages; p++) {
    const page = await pdf.getPage(p);
    const tc = await page.getTextContent();
    const items = tc.items
      .filter((i) => i.str && i.str.trim())
      .map((i) => ({ text: i.str, x: i.transform[4], y: i.transform[5], page: p }));
    pages.push(items);
    page.cleanup();
  }
  await pdf.destroy();
  return pages;
}

function findFlightAnchorsOnPage(items) {
  const rqstItems = nearY(items, FLIGHT_Y.rqst).filter((it) => /^\d{6,}$/.test(it.text.trim()));
  return rqstItems
    .sort((a, b) => a.x - b.x)
    .map((it) => ({ rqst: it.text.trim(), anchorX: it.x }));
}

function buildFlightRanges(anchors) {
  return anchors.map((a, i) => ({
    rqst: a.rqst,
    anchorX: a.anchorX,
    xMin: a.anchorX - 6,
    xMax: i + 1 < anchors.length ? anchors[i + 1].anchorX - 6 : Infinity,
  }));
}

function findPersonColumns(items, xMin, xMax) {
  // Build anchors from rows that are always single-chunk per real person:
  // DOB and DocNumber. This avoids treating overflow chunks (e.g.
  // "Steinbrugg" + "er") as separate columns because they live in the
  // Surname row, not the DOB row.
  const primaryItems = [
    ...nearY(items, PERSON_Y.dob),
    ...nearY(items, PERSON_Y.docNumber),
  ].filter((it) => it.x >= xMin && it.x < xMax);

  let anchors = primaryItems.map((it) => it.x).sort((a, b) => a - b);
  // Dedupe near-identical x positions across the two rows.
  anchors = anchors.reduce((acc, x) => {
    if (acc.length === 0 || x - acc[acc.length - 1] > 5) acc.push(x);
    return acc;
  }, []);

  // Pet entries (and any other persons with no DOB / docNumber) appear in the
  // Surname/Name rows but not in DOB. Add them as columns when they sit far
  // from every primary anchor.
  const surfaceItems = [
    ...nearY(items, PERSON_Y.surname),
    ...nearY(items, PERSON_Y.name),
  ].filter((it) => it.x >= xMin && it.x < xMax);

  for (const it of surfaceItems) {
    if (anchors.every((a) => Math.abs(a - it.x) > 10)) {
      anchors.push(it.x);
    }
  }

  anchors.sort((a, b) => a - b);
  // Final dedupe with a tighter gap to collapse near-duplicate extras.
  return anchors.reduce((acc, x) => {
    if (acc.length === 0 || x - acc[acc.length - 1] > 10) acc.push(x);
    return acc;
  }, []);
}

function extractCellByNearestAnchor(items, fieldY, anchorX, pageAnchors) {
  return joinByX(pickByNearestAnchor(nearY(items, fieldY), anchorX, pageAnchors));
}

function classifyRole(raw) {
  if (!raw) return 'PAX';
  const t = raw.toUpperCase();
  if (t === 'PIC' || t === 'SIC' || t === 'FA') return t;
  return 'PAX';
}

function parseGender(raw) {
  if (!raw) return null;
  if (/M/.test(raw)) return 'M';
  if (/F/.test(raw)) return 'F';
  return null;
}

function splitDocType(raw, fallbackNumber) {
  if (!raw) return { docType: null, docNumber: fallbackNumber || null };
  const trimmed = raw.trim();
  // "NID L0HM42YRP" → type+number combined
  const m = trimmed.match(/^(NID|PP)\s+(\S.*)$/i);
  if (m) return { docType: m[1].toUpperCase(), docNumber: m[2].trim() };
  if (/^(NID|PP)$/i.test(trimmed)) {
    return { docType: trimmed.toUpperCase(), docNumber: fallbackNumber || null };
  }
  return { docType: trimmed.toUpperCase(), docNumber: fallbackNumber || null };
}

function splitCountryWithEmbeddedExpiry(countryRaw, expiryRaw) {
  if (!countryRaw) return { country: null, expiry: expiryRaw || null };
  const m = countryRaw.match(/^(.+?)\s+(\d{1,2}\s+[A-Z][a-z]{2}\s+\d{4})$/);
  if (m) {
    return { country: m[1].trim(), expiry: expiryRaw || m[2] };
  }
  return { country: countryRaw.trim(), expiry: expiryRaw || null };
}

function isPetName(name) {
  return !!name && /^pet\b/i.test(name.trim());
}

function extractPersonsForFlight(items, flight, pageAnchors) {
  const cols = findPersonColumns(items, flight.xMin, flight.xMax);
  const persons = [];
  let petCount = 0;

  for (const colX of cols) {
    const name        = extractCellByNearestAnchor(items, PERSON_Y.name,      colX, pageAnchors);
    const surname     = extractCellByNearestAnchor(items, PERSON_Y.surname,   colX, pageAnchors);

    if (isPetName(name)) {
      petCount += 1;
      continue;
    }

    const role        = extractCellByNearestAnchor(items, PERSON_Y.role,      colX, pageAnchors);
    const gnRaw       = extractCellByNearestAnchor(items, PERSON_Y.gn,        colX, pageAnchors);
    const dobRaw      = extractCellByNearestAnchor(items, PERSON_Y.dob,       colX, pageAnchors);
    const docTypeRaw  = extractCellByNearestAnchor(items, PERSON_Y.docType,   colX, pageAnchors);
    const docNumRaw   = extractCellByNearestAnchor(items, PERSON_Y.docNumber, colX, pageAnchors);
    const countryRaw  = extractCellByNearestAnchor(items, PERSON_Y.country,   colX, pageAnchors);
    const expiryRaw   = extractCellByNearestAnchor(items, PERSON_Y.expiry,    colX, pageAnchors);

    const { docType, docNumber } = splitDocType(docTypeRaw, docNumRaw);
    const { country, expiry }    = splitCountryWithEmbeddedExpiry(countryRaw, expiryRaw);

    const givenNames = name ? name.trim() : null;
    const surn       = surname ? surname.trim() : null;

    if (!givenNames && !surn && !docNumber) continue;

    const fullName = [givenNames, surn].filter(Boolean).join(' ').trim() || null;
    const unmatched = !givenNames && !surn && !!docNumber;

    persons.push({
      givenNames,
      surname: surn,
      fullName,
      role: classifyRole(role),
      gender: parseGender(gnRaw),
      dob: parseDayMonYear(dobRaw),
      docType,
      docNumber: docNumber || null,
      country: country || null,
      docExpiry: parseDayMonYear(expiry),
      unmatched,
    });
  }

  return { persons, petCount };
}

function extractFlightFields(items, flight) {
  // Pax count
  const paxNum = nearY(items, FLIGHT_Y.pax)
    .filter((it) => it.x >= flight.xMin && it.x < flight.xMax)
    .find((it) => /^\d+$/.test(it.text.trim()));
  const paxCount = paxNum ? parseInt(paxNum.text, 10) : 0;

  // Tail # and AC Type share Y row; tail = leftmost (= anchor.x), acType slightly right
  const tailRow = nearY(items, FLIGHT_Y.tailAndAc)
    .filter((it) => it.x >= flight.xMin && it.x < flight.xMax)
    .sort((a, b) => a.x - b.x);

  let tailNumber = null;
  let acType = null;
  if (tailRow.length === 1) {
    // ferry without registration may show only AC type
    if (/^[A-Z]+\d/.test(tailRow[0].text)) tailNumber = tailRow[0].text.trim();
    else acType = tailRow[0].text.trim();
  } else if (tailRow.length >= 2) {
    tailNumber = tailRow[0].text.trim();
    acType     = tailRow[1].text.trim();
  }

  const to        = joinByX(inXRange(nearY(items, FLIGHT_Y.to),     flight.xMin, flight.xMax)) || null;
  const from      = joinByX(inXRange(nearY(items, FLIGHT_Y.from),   flight.xMin, flight.xMax)) || null;
  const etdEtaRaw = joinByX(inXRange(nearY(items, FLIGHT_Y.etdEta), flight.xMin, flight.xMax));
  const [etd, eta] = parseEtdEtaCell(etdEtaRaw);

  const callSignRow = nearY(items, FLIGHT_Y.callSignRow)
    .filter((it) => it.x >= flight.xMin && it.x < flight.xMax)
    .sort((a, b) => a.x - b.x);
  const callSign = callSignRow.find((it) => !/^Operator:/.test(it.text) && !/^Please/.test(it.text))?.text.trim() || null;
  const operatorItem = callSignRow.find((it) => /^Operator:/.test(it.text));
  const operator = operatorItem
    ? operatorItem.text.replace(/^Operator:\s*/, '').trim()
    : null;

  const statusTypeText = joinByX(inXRange(nearY(items, FLIGHT_Y.statusType), flight.xMin, flight.xMax));

  const bottomRow = nearY(items, FLIGHT_Y.bottomRow)
    .filter((it) => it.x >= flight.xMin && it.x < flight.xMax);
  const etdDateRaw = bottomRow.find((it) => /^[A-Z][a-z]{2}\s+\d/.test(it.text))?.text || null;
  const date = parseMonDayYear(etdDateRaw);
  const cancelledFlag = bottomRow.some((it) => /Cancelled/i.test(it.text));

  let type;
  if (cancelledFlag || /Cancelled/i.test(statusTypeText)) type = 'cancelled';
  else if (/Ferry/i.test(statusTypeText)) type = 'ferry';
  else type = 'commercial';

  return {
    rqst: flight.rqst,
    callSign,
    tailNumber,
    acType,
    etd,
    eta,
    from,
    to,
    date,
    type,
    operator,
    paxCount,
    cancelled: type === 'cancelled',
  };
}

function findOrderNumber(pages) {
  for (const items of pages) {
    const it = items.find((i) => /^Order\s*#:\s*/.test(i.text));
    if (it) return it.text.replace(/^Order\s*#:\s*/, '').trim();
  }
  return null;
}

function findReportDate(pages) {
  for (const items of pages) {
    const it = items.find((i) => /^for\s+[A-Z][a-z]{2}\s+\d{1,2}\s+\d{4}$/.test(i.text));
    if (it) return parseMonDayYear(it.text.replace(/^for\s+/, ''));
  }
  return null;
}

function findGeneratedAt(pages) {
  for (const items of pages) {
    const it = items.find((i) => /^Generated on:/.test(i.text));
    if (it) return parseGeneratedAt(it.text);
  }
  return null;
}

/**
 * Parse a NetJets Handling Logistics PDF buffer.
 * @param {Buffer|Uint8Array} pdfBuffer
 * @returns {Promise<object>}
 */
export async function parseNetjetsPDF(pdfBuffer) {
  const pages = await extractPdfPages(pdfBuffer);

  // Drop the legal/stamp page (no flight data) — by content, not just index.
  const flightPages = pages.filter((items) => findFlightAnchorsOnPage(items).length > 0);

  const order = findOrderNumber(pages);
  const reportDate = findReportDate(pages);
  const generatedAt = findGeneratedAt(pages);

  const flights = [];
  const parseWarnings = [];

  for (const items of flightPages) {
    const anchors = findFlightAnchorsOnPage(items);
    const flightsOnPage = buildFlightRanges(anchors);

    // Modified marker: if "*** Modified ***" exists on this page, attribute it
    // to the flight whose anchor.x is closest to the marker.x.
    const modItems = nearY(items, FLIGHT_Y.modified).filter((it) => /Modified/i.test(it.text));
    const modifiedAnchorX = new Set();
    for (const m of modItems) {
      let best = null;
      let bestDist = Infinity;
      for (const fr of flightsOnPage) {
        const d = Math.abs(fr.anchorX - m.x);
        if (d < bestDist) { bestDist = d; best = fr; }
      }
      if (best) modifiedAnchorX.add(best.anchorX);
    }

    // Page-wide anchors = union of every flight's person columns. Used so
    // items at the very right of one flight's last column don't sink items
    // that actually belong to the next flight.
    const pageAnchors = flightsOnPage
      .flatMap((fr) => findPersonColumns(items, fr.xMin, fr.xMax))
      .sort((a, b) => a - b);

    for (const fr of flightsOnPage) {
      const fields = extractFlightFields(items, fr);
      const { persons, petCount } = extractPersonsForFlight(items, fr, pageAnchors);
      const modified = modifiedAnchorX.has(fr.anchorX);

      const unmatchedCount = persons.filter((p) => p.unmatched).length;
      if (unmatchedCount > 0) {
        parseWarnings.push(
          `Flight ${fields.rqst}: ${unmatchedCount} person${unmatchedCount > 1 ? 's' : ''} with no name found (unmatched passport)`,
        );
      }
      if (petCount > 0) {
        parseWarnings.push(
          `Flight ${fields.rqst}: ${petCount} pet entr${petCount > 1 ? 'ies' : 'y'} skipped`,
        );
      }

      flights.push({
        rqst: fields.rqst,
        callSign: fields.callSign,
        tailNumber: fields.tailNumber,
        acType: fields.acType,
        etd: fields.etd,
        eta: fields.eta,
        from: fields.from,
        to: fields.to,
        date: fields.date,
        type: fields.type,
        operator: fields.operator,
        modified,
        paxCount: fields.paxCount,
        cancelled: fields.cancelled,
        persons: fields.cancelled ? [] : persons,
      });
    }
  }

  return {
    source: 'netjets',
    order,
    reportDate,
    generatedAt,
    flights,
    parseWarnings,
  };
}

export default parseNetjetsPDF;
